### ISSUE TITLE
KotterKnifePlugin threw an uncaught Throwable

### ISSUE THREAD

**Issue by qingmei2** [dongjunkun/KotterKnife-Plugin#2]
When I have used the plugin for generating template code, then AndroidStudio throw a dialog:

![image](https://user-images.githubusercontent.com/21142152/29105071-033a4b46-7cfd-11e7-8d56-1bc8ea600cfd.png)
![image](https://user-images.githubusercontent.com/21142152/29105076-0ddcb476-7cfd-11e7-8deb-89cf5c1dd858.png)

And it does not affect the code's  generating.

Maybe it is my IDE's configuration not correct?

**Comment by dongjunkun** [comment]
已修复
