### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by dazeGitHub** [dongjunkun/KotterKnife-Plugin#6]
添加了插件，生成后 bindView 爆红，找不到，您咋找到的？我再添加了  JakeWharton 的  api 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT' 也不好使，在 project 的 build.gradle 里加了 

    repositories {
        maven {
//            url "https://plugins.gradle.org/m2/"
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
        mavenCentral()
        jcenter()
        google()
    }
也不好使，真的服了，你那个咋好使？

**Comment by dongjunkun** [comment]
我是直接将文件copy到工程的

**Comment by dazeGitHub** [comment]
啥玩意，拷贝啥文件，，？能详细说一下吗，？我是kotlin 小白

**Comment by dongjunkun** [comment]
ButterKnife.kt，这个工程就这一个文件，直接拷贝到工程就行了，我也提醒下，这个插件现在也没什么用了，kotlin有更好的方式，不需要那么麻烦

**Comment by dazeGitHub** [comment]
嗯，对的，那个  KotterKnife 中就 ButterKnife.kt 那一个文件，拷贝了果然好使，谢谢，哈哈
